module.exports = {
  someSidebar: {
    "시작하기": [
      "get-started/개요",
      {
        type: "category",
        label: "Cardano 구성 요소",
        items: [
          "get-started/cardano-components",
          "get-started/installing-cardano-node",
          "get-started/running-cardano",
          "get-started/installing-cardano-wallet",
        ],
      },
      {
        type: "category",
        label: "보안 모범 사례",
        items: [
          "get-started/air-gap",
          "get-started/secure-workflow",
        ],
      },
      {
        type: "category",
        label: "빌더 도구",
        items: [
          "get-started/blockfrost",
          "get-started/cardanocli-js",
          "get-started/cardano-wallet-js",
          "get-started/cscli",
          "get-started/dandelion-apis",
          "get-started/koios",
          "get-started/ogmios",
          "get-started/cardanosharp-wallet",
          {
            type: "category",
            label: "Serialization-Lib",
            items: [
              {
                // Generate sidebar automatically from docs/get-started/cardano-serialization-lib
                type: 'autogenerated',
                dirName: 'get-started/cardano-serialization-lib',
              },
            ],
          },
          "get-started/tangocrypto",
        ],
      },
      "get-started/technical-concepts",
      "get-started/testnets-and-devnets",
      "get-started/cardano-developer-community",
    ],
    "Cardano 통합하기": [
      "integrate-cardano/overview",
      "integrate-cardano/creating-wallet-faucet",
      "integrate-cardano/multi-witness-transactions-cli",
      "integrate-cardano/listening-for-payments-cli",
      "integrate-cardano/listening-for-payments-wallet",
      "integrate-cardano/testnet-faucet",
      "integrate-cardano/user-wallet-authentication",
    ],
    "트랜잭션 메타데이터로 빌딩하기": [
      "transaction-metadata/overview",
      "transaction-metadata/how-to-create-a-metadata-transaction-cli",
      "transaction-metadata/how-to-create-a-metadata-transaction-wallet",
      "transaction-metadata/retrieving-metadata",
    ],
    "네이티브 토큰 알아보기": [
      "native-tokens/overview",
      "native-tokens/minting",
      "native-tokens/minting-nfts",
       {
         type: "category",
         label: "Token Registry",
         items: [
           {
             // Generate sidebar automatically from docs/native-tokens/token-registry
             type: 'autogenerated',
             dirName: 'native-tokens/token-registry',
           },
         ],
       },

    ],
    "스마트 컨트랙트 생성하기": [
      "smart-contracts/overview",
      "smart-contracts/marlowe",
      "smart-contracts/plutus",
    ],
    "거버넌스 참여하기": [
      "governance/overview",
       {
         type: "category",
         label: "Cardano Improvement Proposals (CIPs)",
         items: [
           {
             // Generate sidebar automatically from docs/governance/cardano-improvement-proposals
             type: 'autogenerated',
             dirName: 'governance/cardano-improvement-proposals',
           },
         ],
       },
       "governance/project-catalyst",
    ],
    "스테이크 풀 운영하기": [
      "operate-a-stake-pool/overview",
      "operate-a-stake-pool/cardano-key-pairs",
      {
        type: "category",
        label: "Stake Pool Course",
        items: [
          "stake-pool-course/overview",
          "stake-pool-course/introduction-to-cardano",
          "stake-pool-course/lesson-1",
          "stake-pool-course/lesson-2",
          "stake-pool-course/lesson-3",
          "stake-pool-course/lesson-4",
          "stake-pool-course/lesson-5",
          {
            type: "category",
            label: "핸드북",
            items: [
              "stake-pool-course/handbook/grafana-dashboard-tutorial",
              "stake-pool-course/handbook/grafana-loki",
              "stake-pool-course/handbook/setup-virtual-box-written",
              "stake-pool-course/handbook/setup-a-server-on-aws-written",
              "stake-pool-course/handbook/setup-firewall",
              // "stake-pool-course/handbook/install-cardano-node-written",
              // "stake-pool-course/handbook/run-cardano-node-handbook",
              "stake-pool-course/handbook/use-cli",
              "stake-pool-course/handbook/utxo-model",
              "stake-pool-course/handbook/keys-addresses",
              "stake-pool-course/handbook/create-simple-transaction",
              "stake-pool-course/handbook/create-stake-pool-keys",
              "stake-pool-course/handbook/register-stake-keys",
              "stake-pool-course/handbook/generate-stake-pool-keys",
              "stake-pool-course/handbook/configure-topology-files",
              "stake-pool-course/handbook/register-stake-pool-metadata",
              "stake-pool-course/handbook/apply-logging-prometheus",
            ],
          },
          {
            type: "category",
            label: "과제",
            items: [
              "stake-pool-course/assignments/assignment-1",
              "stake-pool-course/assignments/assignment-2",
              "stake-pool-course/assignments/kes_period",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "운영자 도구",
        items: [
          "operate-a-stake-pool/guild-ops-suite",
          "operate-a-stake-pool/ansible-cardano-node",
          "operate-a-stake-pool/frankenwallet",
        ],
      },
      "operate-a-stake-pool/marketing-stake-pool",
    ],
    "개발자 포털에 기여하기": [
      "portal-contributors",
      "portal-contribute",
      "portal-style-guide",
      {
        type: 'link',
        label: 'Changelog',
        href: '/changelog',
      },
    ],
  },
};
